site_name: ClientAI
site_description: A unified client for seamless interaction with multiple AI providers.
site_author: Igor Benav
site_url: https://github.com/igorbenav/clientai

theme:
  name: material
  font:
    text: Ubuntu
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.indexes
    - search.suggest
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: true

nav:
  - ClientAI: index.md
  - Installing: installing.md
  - Quick-Start: quick-start.md
  - Usage:
    - usage/overview.md
    - usage/initialization.md
    - usage/text_generation.md
    - usage/chat_functionality.md
    - usage/multiple_providers.md
    - usage/error_handling.md
  - Examples:
    - Overview: examples/overview.md
    - Examples:
      - AI Dungeon Master: examples/ai_dungeon_master.md
  - Advanced:
    - Overview: advanced/overview.md
    - Specific Providers:
      - Ollama: advanced/ollama_specific.md
      - OpenAI: advanced/openai_specific.md
      - Replicate: advanced/replicate_specific.md
    - Error Handling: advanced/error_handling.md
  - API Reference:
    - Overview: api/overview.md
    - ClientAI: api/clientai.md
    - AIProvider: api/ai_provider.md
    - Specific Providers:
      - Ollama: api/ollama_provider.md
      - OpenAI: api/openai_provider.md
      - Replicate: api/replicate_provider.md
  - Community:
    - Overview: community/overview.md
    - Contributing: community/CONTRIBUTING.md
    - Code of Conduct: community/CODE_OF_CONDUCT.md
    - License: community/LICENSE.md
  - Extending: extending.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

repo_name: igorbenav/clientai
repo_url: https://github.com/igorbenav/clientai
edit_uri: edit/main/docs/

extra_css:
  - stylesheets/extra.css